from __future__ import annotations

from typing import Any


DECAY_MODE_CHANNEL: dict[str, Any] = {
    "key": "operation_mode",
    "channel_id": 2418,
    "pv": "RNG:OPERATION:MODE:bo",
    "table": "sample_raw",
    "value_field": "num_val",
    "subsystem": "operation",
    "diagnostic_role": "mode_state",
    "description": "储存环运行模式开关；0 表示恒流模式中断，1 表示恒流模式恢复。",
    "normal_value": 1,
    "abnormal_rule": "equals_0",
    "value_map": {
        0: "constant_current_interrupted",
        1: "constant_current_normal",
    },
}

DECAY_ENABLE_CHANNEL: dict[str, Any] = {
    "key": "topoff_alarm_enable",
    "channel_id": 2419,
    "pv": "RNG:TOPOFF:ALARM:ENABLE",
    "table": "sample_raw",
    "value_field": "num_val",
    "subsystem": "topoff",
    "diagnostic_role": "alarm_enable",
    "description": "恒流报警链路使能状态；第一版默认按已使能处理。",
    "normal_value": 1,
    "abnormal_rule": "equals_0",
    "value_map": {
        0: "topoff_alarm_disabled",
        1: "topoff_alarm_enabled",
    },
}

BEAM_CURRENT_CHANNEL: dict[str, Any] = {
    "key": "beam_current",
    "channel_id": None,
    "pv": "RNG:BEAM:CURR",
    "table": "sample",
    "value_field": "float_val",
    "subsystem": "beam",
    "diagnostic_role": "beam_curve",
    "description": "储存环束流强度连续量，用于判断束流表现为掉束、decay-like 或正常。",
    "normal_value": None,
    "abnormal_rule": "continuous_curve",
    "value_map": {},
}


DECAY_ALARM_CHANNELS: dict[str, dict[str, Any]] = {
    "topoff_dm_neutron_error": {
        "key": "topoff_dm_neutron_error",
        "channel_id": 2420,
        "pv": "RNG:TOPOFF:DM:Neutron:Err:mbbo",
        "subsystem": "DM",
        "diagnostic_role": "root_cause_alarm",
        "description": "中子剂量超标报警，用于判断恒流中断是否由剂量报警触发。",
        "normal_value": 0,
        "abnormal_rule": "nonzero",
        "value_map": {
            0: "DMNeutron_NoOverdose",
            1: "DMNeutron6_Overdose",
            2: "DMNeutron7_Overdose",
            3: "DMNeutron8_Overdose",
            4: "DMNeutron9_Overdose",
            5: "DMNeutron10_Overdose",
            6: "DMNeutron11_Overdose",
            7: "DMNeutron12_Overdose",
            8: "DMNeutron13_Overdose",
            9: "DMNeutron14_Overdose",
            10: "DMNeutron15_Overdose",
            11: "DMNeutron16_Overdose",
        },
    },
    "topoff_dm_gamma_error": {
        "key": "topoff_dm_gamma_error",
        "channel_id": 2421,
        "pv": "RNG:TOPOFF:DM:Gamma:Err:mbbo",
        "subsystem": "DM",
        "diagnostic_role": "root_cause_alarm",
        "description": "Gamma 剂量超标报警，用于判断恒流中断是否由剂量报警触发。",
        "normal_value": 0,
        "abnormal_rule": "nonzero",
        "value_map": {
            0: "DMGamma_NoOverdose",
            1: "DMGamma6_Overdose",
            2: "DMGamma7_Overdose",
            3: "DMGamma8_Overdose",
            4: "DMGamma9_Overdose",
            5: "DMGamma10_Overdose",
            6: "DMGamma11_Overdose",
            7: "DMGamma12_Overdose",
            8: "DMGamma13_Overdose",
            9: "DMGamma14_Overdose",
            10: "DMGamma15_Overdose",
            11: "DMGamma16_Overdose",
        },
    },
    "topoff_injection_efficiency_error": {
        "key": "topoff_injection_efficiency_error",
        "channel_id": 2422,
        "pv": "RNG:TOPOFF:IE:Err:mbbo",
        "subsystem": "injection",
        "diagnostic_role": "root_cause_alarm",
        "description": "注入效率报警，用于判断恒流中断是否由注入效率低触发。",
        "normal_value": 0,
        "abnormal_rule": "nonzero",
        "value_map": {0: "InjectingEfficiencyNormal", 1: "Injecting Efficiency Low"},
    },
    "topoff_injection_system_error": {
        "key": "topoff_injection_system_error",
        "channel_id": 2423,
        "pv": "RNG:TOPOFF:RI:Err:mbbo",
        "subsystem": "injection",
        "diagnostic_role": "root_cause_alarm",
        "description": "注入系统报警，用于判断恒流中断是否由 kicker 或 septum 故障触发。",
        "normal_value": 0,
        "abnormal_rule": "nonzero",
        "value_map": {
            0: "Injection System Normal",
            1: "Kick1_Err",
            2: "Kick2_Err",
            3: "Kick3_Err",
            4: "Kick4_Err",
            5: "Septum_Err",
        },
    },
    "topoff_mps_error": {
        "key": "topoff_mps_error",
        "channel_id": 2424,
        "pv": "RNG:TOPOFF:MPS:Err:mbbo",
        "subsystem": "MPS",
        "diagnostic_role": "root_cause_alarm",
        "description": "主电源系统报警，用于判断恒流中断是否由 MPS 故障触发。",
        "normal_value": 0,
        "abnormal_rule": "nonzero",
        "value_map": {
            0: "MPS Normal",
            1: "INJ_MPS_Err",
            2: "QPU_MPS_Err",
            3: "SSS_MPS_Err",
            4: "WIG_MPS_Err",
            5: "U92_MPS_Err",
            6: "IVU_MPS_Err",
            7: "EPU_MPS_Err",
            8: "RFC_MPS_Err",
            9: "BM_Err",
        },
    },
    "topoff_tps_error": {
        "key": "topoff_tps_error",
        "channel_id": 2425,
        "pv": "RNG:TOPOFF:TPS:Err:mbbo",
        "subsystem": "TPS",
        "diagnostic_role": "root_cause_alarm",
        "description": "TPS 报警，用于判断恒流中断是否由 TPS 或 BMPS 故障触发。",
        "normal_value": 0,
        "abnormal_rule": "nonzero",
        "value_map": {
            0: "TPS Normal",
            1: "TPS1_Err",
            2: "TPS2_Err",
            3: "TPS3_Err",
            4: "TPS4_Err",
            5: "TPS5_Err",
            6: "TPS6_Err",
            7: "TPS7_Err",
            8: "TPS8_Err",
            9: "TPS9_Err",
            10: "TPS10_Err",
            11: "TPS11_Err",
            12: "TPS12_Err",
            13: "BMPS1_Err",
            14: "BMPS3_Err",
        },
    },
    "topoff_beam_error": {
        "key": "topoff_beam_error",
        "channel_id": 2426,
        "pv": "RNG:TOPOFF:BEAM:Err:mbbo",
        "subsystem": "beam",
        "diagnostic_role": "root_cause_alarm",
        "description": "束流报警状态量，不是束流曲线；用于判断恒流中断是否由低流强或束团异常触发。",
        "normal_value": 0,
        "abnormal_rule": "nonzero",
        "value_map": {0: "Current Normal", 1: "Low Current", 2: "Bunch_Err"},
    },
    "topoff_kly_error": {
        "key": "topoff_kly_error",
        "channel_id": 2427,
        "pv": "RNG:TOPOFF:KLY:Err:mbbo",
        "subsystem": "KLY",
        "diagnostic_role": "root_cause_alarm",
        "description": "KLY 调制器故障报警，用于判断恒流中断是否由速调管调制器故障触发。",
        "normal_value": 0,
        "abnormal_rule": "nonzero",
        "value_map": {
            0: "KLY_Normal",
            1: "KLY1_Err",
            2: "KLY2_Err",
            3: "KLY3_Err",
            4: "KLY4_Err",
            5: "KLY5_Err",
            6: "KLY6_Err",
            7: "KLY7_Err",
            8: "KLY8_Err",
            9: "KLY9_Err",
        },
    },
    "bending_magnet_temperature_alarm": {
        "key": "bending_magnet_temperature_alarm",
        "channel_id": 2428,
        "pv": "RNG:BTemp:alarm:bi",
        "subsystem": "temperature",
        "diagnostic_role": "root_cause_alarm",
        "description": "二极铁温度报警，用于判断恒流中断是否由磁铁温度异常触发。",
        "normal_value": 0,
        "abnormal_rule": "equals_1",
        "value_map": {0: "normal", 1: "bending_magnet_temperature_alarm"},
    },
    "sextupole_temperature_alarm": {
        "key": "sextupole_temperature_alarm",
        "channel_id": 2429,
        "pv": "RNG:STemp:alarm:bi",
        "subsystem": "temperature",
        "diagnostic_role": "root_cause_alarm",
        "description": "六极铁温度报警，用于判断恒流中断是否由磁铁温度异常触发。",
        "normal_value": 0,
        "abnormal_rule": "equals_1",
        "value_map": {0: "normal", 1: "sextupole_temperature_alarm"},
    },
    "quadrupole_temperature_alarm": {
        "key": "quadrupole_temperature_alarm",
        "channel_id": 2430,
        "pv": "RNG:QTemp:alarm:bi",
        "subsystem": "temperature",
        "diagnostic_role": "root_cause_alarm",
        "description": "四极铁温度报警，用于判断恒流中断是否由磁铁温度异常触发。",
        "normal_value": 0,
        "abnormal_rule": "equals_1",
        "value_map": {0: "normal", 1: "quadrupole_temperature_alarm"},
    },
}

for _channel in DECAY_ALARM_CHANNELS.values():
    _channel.setdefault("table", "sample_raw")
    _channel.setdefault("value_field", "num_val")

DECAY_CHANNELS: dict[str, dict[str, Any]] = {
    DECAY_MODE_CHANNEL["key"]: DECAY_MODE_CHANNEL,
    DECAY_ENABLE_CHANNEL["key"]: DECAY_ENABLE_CHANNEL,
    BEAM_CURRENT_CHANNEL["key"]: BEAM_CURRENT_CHANNEL,
    **DECAY_ALARM_CHANNELS,
}


def get_decay_channel(key: str) -> dict[str, Any]:
    return DECAY_CHANNELS[key]


def get_decay_alarm_channels() -> list[dict[str, Any]]:
    return list(DECAY_ALARM_CHANNELS.values())
